// This file is auto-generated by `npx convex dev`.
// Run that command to replace this stub with real types.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = new Proxy(
  {},
  {
    get(_, ns) {
      return new Proxy(
        {},
        {
          get(_, fn) {
            return `${String(ns)}:${String(fn)}`;
          },
        }
      );
    },
  }
);
