// Auto-generated by `npx convex dev` — do not edit manually.
// This stub is replaced when Convex is initialized.
export type DataModel = Record<string, never>;
export type Id<T extends string> = string & { __tableName: T };
