// Auto-generated by `npx convex dev` — do not edit manually.
// This stub is replaced when Convex is initialized.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const query = (def: any) => def;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const mutation = (def: any) => def;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const action = (def: any) => def;
